#!/usr/bin/python3
def multiply_list_map(my_list=[], number=0):
#new_list = [map(lambda my_list: my_list[i] * number for i in len(my_list))]
    new_list = []
    for i in my list:
       new_list += i * number
    return new_list
