#!/usr/bin/python3
word = "Holberton"
word_first_3 = world[0:4]
word_last_2 = world[7: ]
middle_word = world[1:8]
print(f"First 3 letters: {word_first_3}")
print(f"Last 2 letters: {word_last_2}")
print(f"Middle word: {middle_word}")
